export default {
  FETCHING_CURRENCIES: 'FETCHING_CURRENCIES',
  FETCHING_CURRENCIES_SUCCESS: 'FETCHING_CURRENCIES_SUCCESS',
  FETCHING_CURRENCIES_ERROR: 'FETCHING_CURRENCIES_ERROR',

  CREATING_CURRENCY: 'CREATING_CURRENCY',
  CREATING_CURRENCY_SUCCESS: 'CREATING_CURRENCY_SUCCESS',
  CREATING_CURRENCY_ERROR: 'CREATING_CURRENCY_ERROR',

  UPDATING_CURRENCY: 'UPDATING_CURRENCY',
  UPDATING_CURRENCY_SUCCESS: 'UPDATING_CURRENCY_SUCCESS',
  UPDATING_CURRENCY_ERROR: 'UPDATING_CURRENCY_ERROR',

  DELETING_CURRENCY: 'DELETING_CURRENCY',
  DELETING_CURRENCY_SUCCESS: 'DELETING_CURRENCY_SUCCESS',
  DELETING_CURRENCY_ERROR: 'DELETING_CURRENCY_ERROR',

  RESET_CURRENCY_INFO: 'RESET_CURRENCY_INFO',
};
