export default {
  FETCHING_CLIENTS: 'FETCHING_CLIENTS',
  FETCHING_CLIENTS_SUCCESS: 'FETCHING_CLIENTS_SUCCESS',
  FETCHING_CLIENTS_ERROR: 'FETCHING_CLIENTS_ERROR',

  CREATING_CLIENT: 'CREATING_CLIENT',
  CREATING_CLIENT_SUCCESS: 'CREATING_CLIENT_SUCCESS',
  CREATING_CLIENT_ERROR: 'CREATING_CLIENT_ERROR',

  UPDATING_CLIENT: 'UPDATING_CLIENT',
  UPDATING_CLIENT_SUCCESS: 'UPDATING_CLIENT_SUCCESS',
  UPDATING_CLIENT_ERROR: 'UPDATING_CLIENT_ERROR',

  DELETING_CLIENT: 'DELETING_CLIENT',
  DELETING_CLIENT_SUCCESS: 'DELETING_CLIENT_SUCCESS',
  DELETING_CLIENT_ERROR: 'DELETING_CLIENT_ERROR',

  FETCHING_PROFILE: 'FETCHING_PROFILE',
  FETCHING_PROFILE_SUCCESS: 'FETCHING_PROFILE_SUCCESS',
  FETCHING_PROFILE_ERROR: 'FETCHING_PROFILE_ERROR',

  RESET_CLIENT_INFO: 'RESET_CLIENT_INFO',
};
