export default {
  FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
  FETCHING_CATEGORIES_SUCCESS: 'FETCHING_CATEGORIES_SUCCESS',
  FETCHING_CATEGORIES_ERROR: 'FETCHING_CATEGORIES_ERROR',

  CREATING_CATEGORY: 'CREATING_CATEGORY',
  CREATING_CATEGORY_SUCCESS: 'CREATING_CATEGORY_SUCCESS',
  CREATING_CATEGORY_ERROR: 'CREATING_CATEGORY_ERROR',

  UPDATING_CATEGORY: 'UPDATING_CATEGORY',
  UPDATING_CATEGORY_SUCCESS: 'UPDATING_CATEGORY_SUCCESS',
  UPDATING_CATEGORY_ERROR: 'UPDATING_CATEGORY_ERROR',

  DELETING_CATEGORY: 'DELETING_CATEGORY',
  DELETING_CATEGORY_SUCCESS: 'DELETING_CATEGORY_SUCCESS',
  DELETING_CATEGORY_ERROR: 'DELETING_CATEGORY_ERROR',

  RESET_CATEGORY_INFO: 'RESET_CATEGORY_INFO',
};
