export default {
  FETCHING_MOVEMENTS: 'FETCHING_MOVEMENTS',
  FETCHING_MOVEMENTS_SUCCESS: 'FETCHING_MOVEMENTS_SUCCESS',
  FETCHING_MOVEMENTS_ERROR: 'FETCHING_MOVEMENTS_ERROR',

  CREATING_MOVEMENT: 'CREATING_MOVEMENT',
  CREATING_MOVEMENT_SUCCESS: 'CREATING_MOVEMENT_SUCCESS',
  CREATING_MOVEMENT_ERROR: 'CREATING_MOVEMENT_ERROR',

  UPDATING_MOVEMENT: 'UPDATING_MOVEMENT',
  UPDATING_MOVEMENT_SUCCESS: 'UPDATING_MOVEMENT_SUCCESS',
  UPDATING_MOVEMENT_ERROR: 'UPDATING_MOVEMENT_ERROR',

  DELETING_MOVEMENT: 'DELETING_MOVEMENT',
  DELETING_MOVEMENT_SUCCESS: 'DELETING_MOVEMENT_SUCCESS',
  DELETING_MOVEMENT_ERROR: 'DELETING_MOVEMENT_ERROR',

  RESET_MOVEMENT_INFO: 'RESET_MOVEMENT_INFO',
};
