export default {
  FETCHING_BALANCE: 'FETCHING_BALANCE',
  FETCHING_BALANCE_SUCCESS: 'FETCHING_BALANCE_SUCCESS',
  FETCHING_BALANCE_ERROR: 'FETCHING_BALANCE_ERROR',

  FETCHING_EXPENSES_FORECAST: 'FETCHING_EXPENSES_FORECAST',
  FETCHING_EXPENSES_FORECAST_SUCCESS: 'FETCHING_EXPENSES_FORECAST_SUCCESS',
  FETCHING_EXPENSES_FORECAST_ERROR: 'FETCHING_EXPENSES_FORECAST_ERROR',

  FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY:
    'FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY',
  FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY_SUCCESS:
    'FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY_SUCCESS',
  FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY_ERROR:
    'FETCHING_EXPENSES_BY_MONTHS_BY_CATEGORY_ERROR',

  FETCHING_EXPENSES_BY_MONTHS_BY_DAY: 'FETCHING_EXPENSES_BY_MONTHS_BY_DAY',
  FETCHING_EXPENSES_BY_MONTHS_BY_DAY_SUCCESS:
    'FETCHING_EXPENSES_BY_MONTHS_BY_DAY_SUCCESS',
  FETCHING_EXPENSES_BY_MONTHS_BY_DAY_ERROR:
    'FETCHING_EXPENSES_BY_MONTHS_BY_DAY_ERROR',

  FETCHING_REPORT_MOVEMENTS: 'FETCHING_REPORT_MOVEMENTS',
  FETCHING_REPORT_MOVEMENTS_SUCCESS: 'FETCHING_REPORT_MOVEMENTS_SUCCESS',
  FETCHING_REPORT_MOVEMENTS_ERROR: 'FETCHING_REPORT_MOVEMENTS_ERROR',
};
